import torch

def apply_input_trigger(
    x,
    trigger_type: str = "torus",
    n_trigger: int = 128,
    trigger_scale: float = 0.10,
    trigger_position: str = "fixed_global",
    center=None,
    seed=None,
    return_info: bool = False,
    shuffle: bool = False,
):
    """
    x: [B, N, 3]

    Stage 0 behavior:
        placement_rule = replace_last_K
        fixed global coordinate center
        no shuffle
        no resampling after concat

    If return_info=False:
        return x_trigger: [B, N, 3]

    If return_info=True:
        return x_trigger: [B, N, 3], trigger_info: dict

    Note on determinism/seed:
        The torus and ring triggers generated by tools.torus are fully deterministic 
        because they use regular grid/linspace mapping over periodic parameter spaces. 
        Thus, the seed parameter is accepted but ignored, and outputs are naturally identical.
    """
    if shuffle:
        raise ValueError("shuffle must be False under Stage 0")
    if trigger_position != "fixed_global":
        raise ValueError("trigger_position must be 'fixed_global' under Stage 0")
    if len(x.shape) != 3 or x.shape[2] != 3:
        raise ValueError("x must be of shape [B, N, 3]")

    B, N, _ = x.shape
    K = n_trigger

    if K <= 0 or K > N:
        raise ValueError(f"n_trigger must be between 1 and N (got {K}, N={N})")

    if center is None:
        center = (0.6, 0.6, 0.6)

    device = x.device
    dtype = x.dtype

    if trigger_type == "torus":
        from tools.torus import generate_torus_trigger_full
        major_radius = trigger_scale
        minor_radius = trigger_scale * 0.25
        trigger_full = generate_torus_trigger_full(
            batch_size=B,
            n_points=N,
            n_trigger=K,
            major_radius=major_radius,
            minor_radius=minor_radius,
            center=center,
            device=device,
            dtype=dtype,
        )
    elif trigger_type == "ring":
        from tools.torus import generate_ring_trigger_full
        trigger_full = generate_ring_trigger_full(
            batch_size=B,
            n_points=N,
            n_trigger=K,
            radius=trigger_scale,
            center=center,
            device=device,
            dtype=dtype,
        )
    else:
        raise ValueError(f"Unsupported trigger_type for input triggers: {trigger_type}")

    # Only extract the exact K trigger points generated at the beginning of the tensor
    trigger_points = trigger_full[:, :K, :]

    # Replace last K points
    x_keep = x[:, :N - K, :]
    x_trigger = torch.cat([x_keep, trigger_points], dim=1)

    if not return_info:
        return x_trigger

    keep_indices = list(range(0, N - K))
    drop_indices = list(range(N - K, N))
    trigger_indices = list(range(N - K, N))

    trigger_mask = torch.zeros(B, N, dtype=torch.bool, device=device)
    trigger_mask[:, N - K:] = True

    trigger_info = {
        "trigger_type": trigger_type,
        "n_trigger": K,
        "placement_rule": "replace_last_K",
        "keep_indices": keep_indices,
        "drop_indices": drop_indices,
        "trigger_indices": trigger_indices,
        "trigger_mask": trigger_mask,
        "trigger_points": trigger_points,
        "trigger_position": trigger_position,
        "center": center,
        "coordinate_frame": "global",
        "trigger_scale": trigger_scale,
        "shuffle": shuffle,
        "resample_after_concat": False,
    }

    return x_trigger, trigger_info
